Repository ufrpe-devs/ufrpe-devs.github.io, pull requests merged in 2021-09, with the labels that each got.

#7 [Feature] Theme tokens
  .eslintrc.json
  .husky/pre-commit
  .prettierrc
  README.md
  components/Navbar/index.jsx
  next.config.js
  package.json
  pages/_app.js
  pages/index.jsx
  styles/Home.module.css
  styles/globals.css
  styles/theme.js
  yarn.lock
Labels: enhancement

#8 [Feature] Topo do site
  .github/workflows/deploy.yml
  components/Home/components/Hero/index.jsx
  components/Home/components/Hero/styles.js
  components/Home/index.jsx
  components/Page/components/Navbar/index.jsx
  components/Page/components/Navbar/styles.js
  components/Page/components/index.jsx
  components/Page/index.jsx
  images/community.svg
  images/index.js
  images/logo-rectangle.svg
  images/logo-small.svg
  next.config.js
  package-lock.json
  package.json
  pages/_document.js
  pages/index.jsx
  styles/theme.js
Labels: enhancement

#11 [Feature] Footer
  .gitignore
  components/Footer/index.jsx
  components/Footer/styles.js
  components/Hero/index.jsx
  components/Hero/styles.js
  components/Home/index.jsx
  components/Navbar/index.jsx
  components/Navbar/styles.js
  components/Page/components/index.jsx
  components/Page/index.jsx
  components/Template/index.jsx
  images/astronaut-logo.svg
  images/hack-club.svg
  images/index.js
  package-lock.json
  pages/_document.js
  pages/index.jsx
  styles/theme.js
Labels: enhancement

#13 [Fix] Menu behaviour
  components/Navbar/index.jsx
Labels: bug

#15 [Refactor] Mudança para Gatsby
  .eslintrc.json
  .github/workflows/deploy.yml
  .gitignore
  .husky/pre-commit
  .prettierignore
  .prettierrc
  LICENSE
  README.md
  components/Template/index.jsx
  gatsby-browser.js
  gatsby-config.js
  gatsby-ssr.js
  images/community.svg
  images/index.js
  next.config.js
  package-lock.json
  package.json
  pages/_app.js
  pages/_document.js
  pages/index.jsx
  public/.nojekyll
  public/favicon.ico
  public/vercel.svg
  src/assets/astronaut-logo.svg
  src/assets/community.svg
  src/assets/hack-club.svg
  src/assets/logo-rectangle.svg
  src/assets/logo-small.svg
  src/components/Footer/index.jsx
  src/components/Footer/styles.js
  src/components/Hero/index.jsx
  src/components/Hero/styles.js
  src/components/Navbar/index.jsx
  src/components/Navbar/styles.js
  src/components/layout.js
  src/components/seo.js
  src/images/icon.png
  src/pages/404.js
  src/pages/index.js
  src/styles/theme.js
  src/wrapper.jsx
  yarn.lock
Labels: bug, enhancement
